<a href="https://colab.research.google.com/github/GustavoAdolf0/data_contest/blob/main/info_stores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# agregar info al archivo stores

se agregara info de poblaci√≥n y densidad para mejorar el modelo

In [ ]:
import numpy as np
import pandas as pd
from google.colab import drive

In [ ]:
path = "drive/MyDrive/store_sales/"

In [ ]:
# data del kaggle

stores= pd.read_csv(path+"stores.csv")

In [ ]:
#revisar data

stores

    store_nbr           city                           state type  cluster
0           1          Quito                       Pichincha    D       13
1           2          Quito                       Pichincha    D       13
2           3          Quito                       Pichincha    D        8
3           4          Quito                       Pichincha    D        9
4           5  Santo Domingo  Santo Domingo de los Tsachilas    D        4
5           6          Quito                       Pichincha    D       13
6           7          Quito                       Pichincha    D        8
7           8          Quito                       Pichincha    D        8
8           9          Quito                       Pichincha    B        6
9          10          Quito                       Pichincha    C       15
10         11        Cayambe                       Pichincha    B        6
11         12      Latacunga                        Cotopaxi    C       15
12         13      Latacunga                        Cotopaxi    C       15
13         14       Riobamba                      Chimborazo    C        7
14         15         Ibarra                        Imbabura    C       15
15         16  Santo Domingo  Santo Domingo de los Tsachilas    C        3
16         17          Quito                       Pichincha    C       12
17         18          Quito                       Pichincha    B       16
18         19       Guaranda                         Bolivar    C       15
19         20          Quito                       Pichincha    B        6
20         21  Santo Domingo  Santo Domingo de los Tsachilas    B        6
21         22           Puyo                         Pastaza    C        7
22         23         Ambato                      Tungurahua    D        9
23         24      Guayaquil                          Guayas    D        1
24         25        Salinas                     Santa Elena    D        1
25         26      Guayaquil                          Guayas    D       10
26         27          Daule                          Guayas    D        1
27         28      Guayaquil                          Guayas    E       10
28         29      Guayaquil                          Guayas    E       10
29         30      Guayaquil                          Guayas    C        3
30         31       Babahoyo                        Los Rios    B       10
31         32      Guayaquil                          Guayas    C        3
32         33        Quevedo                        Los Rios    C        3
33         34      Guayaquil                          Guayas    B        6
34         35         Playas                          Guayas    C        3
35         36       Libertad                          Guayas    E       10
36         37         Cuenca                           Azuay    D        2
37         38           Loja                            Loja    D        4
38         39         Cuenca                           Azuay    B        6
39         40        Machala                          El Oro    C        3
40         41        Machala                          El Oro    D        4
41         42         Cuenca                           Azuay    D        2
42         43     Esmeraldas                      Esmeraldas    E       10
43         44          Quito                       Pichincha    A        5
44         45          Quito                       Pichincha    A       11
45         46          Quito                       Pichincha    A       14
46         47          Quito                       Pichincha    A       14
47         48          Quito                       Pichincha    A       14
48         49          Quito                       Pichincha    A       11
49         50         Ambato                      Tungurahua    A       14
50         51      Guayaquil                          Guayas    A       17
51         52          Manta                          Manabi    A       11
52         53          Manta                          Manabi    D       13
53         54      El Carmen                          Manabi    C        3

In [ ]:
#al revisar la data de las tiendas se puede a√±adir info acerca de ingresos o poblaci√≥n del sector, adem√°s la ubicaci√≥n se debe usar un one hot encoder, cluster es una clasificaci√≥n de tiendas similares

# Datos ubicaci√≥n

se va a enriquecer los datos de las tiendas, a√±adiendo informacion como densidad poblacional y poblaci√≥n

In [ ]:
stores

    store_nbr           city                           state type  cluster
0           1          Quito                       Pichincha    D       13
1           2          Quito                       Pichincha    D       13
2           3          Quito                       Pichincha    D        8
3           4          Quito                       Pichincha    D        9
4           5  Santo Domingo  Santo Domingo de los Tsachilas    D        4
5           6          Quito                       Pichincha    D       13
6           7          Quito                       Pichincha    D        8
7           8          Quito                       Pichincha    D        8
8           9          Quito                       Pichincha    B        6
9          10          Quito                       Pichincha    C       15
10         11        Cayambe                       Pichincha    B        6
11         12      Latacunga                        Cotopaxi    C       15
12         13      Latacunga                        Cotopaxi    C       15
13         14       Riobamba                      Chimborazo    C        7
14         15         Ibarra                        Imbabura    C       15
15         16  Santo Domingo  Santo Domingo de los Tsachilas    C        3
16         17          Quito                       Pichincha    C       12
17         18          Quito                       Pichincha    B       16
18         19       Guaranda                         Bolivar    C       15
19         20          Quito                       Pichincha    B        6
20         21  Santo Domingo  Santo Domingo de los Tsachilas    B        6
21         22           Puyo                         Pastaza    C        7
22         23         Ambato                      Tungurahua    D        9
23         24      Guayaquil                          Guayas    D        1
24         25        Salinas                     Santa Elena    D        1
25         26      Guayaquil                          Guayas    D       10
26         27          Daule                          Guayas    D        1
27         28      Guayaquil                          Guayas    E       10
28         29      Guayaquil                          Guayas    E       10
29         30      Guayaquil                          Guayas    C        3
30         31       Babahoyo                        Los Rios    B       10
31         32      Guayaquil                          Guayas    C        3
32         33        Quevedo                        Los Rios    C        3
33         34      Guayaquil                          Guayas    B        6
34         35         Playas                          Guayas    C        3
35         36       Libertad                          Guayas    E       10
36         37         Cuenca                           Azuay    D        2
37         38           Loja                            Loja    D        4
38         39         Cuenca                           Azuay    B        6
39         40        Machala                          El Oro    C        3
40         41        Machala                          El Oro    D        4
41         42         Cuenca                           Azuay    D        2
42         43     Esmeraldas                      Esmeraldas    E       10
43         44          Quito                       Pichincha    A        5
44         45          Quito                       Pichincha    A       11
45         46          Quito                       Pichincha    A       14
46         47          Quito                       Pichincha    A       14
47         48          Quito                       Pichincha    A       14
48         49          Quito                       Pichincha    A       11
49         50         Ambato                      Tungurahua    A       14
50         51      Guayaquil                          Guayas    A       17
51         52          Manta                          Manabi    A       11
52         53          Manta                          Manabi    D       13
53         54      El Carmen                          Manabi    C        3

In [ ]:
#se traeran los datos provincia
datos_provincia= pd.read_excel(path+"info_ecuador.xlsx")
datos_provincia

       #         Ciudad  ... pob_provincia2020     %_pob
0      1      Guayaquil  ...           4387434  0.519368
1      2          Quito  ...           3228233  0.498023
2      3         Cuenca  ...            881394  0.374325
3      4  Santo Domingo  ...            458580  0.590682
4      5        Machala  ...            715751  0.323101
..   ...            ...  ...               ...       ...
216  217         Olmedo  ...            521154  0.001194
217  218          D√©leg  ...            281396  0.002054
218  219      La Bonita  ...            230503  0.002382
219  220         El Pan  ...            881394  0.000551
220  221       Tiputini  ...            161338  0.002857

[221 rows x 10 columns]

In [ ]:
#rename para hacer el join m√°s sencillo
datos_provincia= datos_provincia.rename(columns={'Province': 'state', "Ciudad":"city"})
datos_provincia.head()

   #           city  ... pob_provincia2020     %_pob
0  1      Guayaquil  ...           4387434  0.519368
1  2          Quito  ...           3228233  0.498023
2  3         Cuenca  ...            881394  0.374325
3  4  Santo Domingo  ...            458580  0.590682
4  5        Machala  ...            715751  0.323101

[5 rows x 10 columns]

In [ ]:
#se guarda en lista los estados de ecuador y tiendas
city_ecuador= sorted(datos_provincia.city.unique())
city_stores=sorted(stores.city.unique())
type(city_ecuador)

list

In [ ]:
city_stores

['Ambato',
 'Babahoyo',
 'Cayambe',
 'Cuenca',
 'Daule',
 'El Carmen',
 'Esmeraldas',
 'Guaranda',
 'Guayaquil',
 'Ibarra',
 'Latacunga',
 'Libertad',
 'Loja',
 'Machala',
 'Manta',
 'Playas',
 'Puyo',
 'Quevedo',
 'Quito',
 'Riobamba',
 'Salinas',
 'Santo Domingo']

In [ ]:
len(city_stores), len(city_ecuador)

(22, 220)

In [ ]:
type(city_stores), type(city_ecuador)

(list, list)

In [ ]:
no_city=[]

for i in range(len(city_stores)):
   if city_stores[i] not in city_ecuador:
     no_city.append(city_stores[i])
print(no_city)

#for que revisa si algo est√° en la lista y luego lo a√±ade a otra lista e imprime

[]

In [ ]:
datos_provincia.head()

   #           city  ... pob_provincia2020     %_pob
0  1      Guayaquil  ...           4387434  0.519368
1  2          Quito  ...           3228233  0.498023
2  3         Cuenca  ...            881394  0.374325
3  4  Santo Domingo  ...            458580  0.590682
4  5        Machala  ...            715751  0.323101

[5 rows x 10 columns]

In [ ]:
stores=pd.merge(stores, datos_provincia[["city","Poblaci√≥n(2010)","capital",	"den_provincia",	"cantones",	"pob_provincia2020",	"%_pob"]], on="city", how="left")

In [ ]:
len(stores)

54

In [ ]:
stores

    store_nbr           city  ... pob_provincia2020     %_pob
0           1          Quito  ...           3228233  0.498023
1           2          Quito  ...           3228233  0.498023
2           3          Quito  ...           3228233  0.498023
3           4          Quito  ...           3228233  0.498023
4           5  Santo Domingo  ...            458580  0.590682
5           6          Quito  ...           3228233  0.498023
6           7          Quito  ...           3228233  0.498023
7           8          Quito  ...           3228233  0.498023
8           9          Quito  ...           3228233  0.498023
9          10          Quito  ...           3228233  0.498023
10         11        Cayambe  ...           3228233  0.012090
11         12      Latacunga  ...            488716  0.130632
12         13      Latacunga  ...            488716  0.130632
13         14       Riobamba  ...            524004  0.279242
14         15         Ibarra  ...            476257  0.276859
15         16  Santo Domingo  ...            458580  0.590682
16         17          Quito  ...           3228233  0.498023
17         18          Quito  ...           3228233  0.498023
18         19       Guaranda  ...            209933  0.113722
19         20          Quito  ...           3228233  0.498023
20         21  Santo Domingo  ...            458580  0.590682
21         22           Puyo  ...            114202  0.293839
22         23         Ambato  ...            590600  0.279690
23         24      Guayaquil  ...           4387434  0.519368
24         25        Salinas  ...            401178  0.086543
25         26      Guayaquil  ...           4387434  0.519368
26         27          Daule  ...           4387434  0.014848
27         28      Guayaquil  ...           4387434  0.519368
28         29      Guayaquil  ...           4387434  0.519368
29         30      Guayaquil  ...           4387434  0.519368
30         31       Babahoyo  ...            921763  0.097846
31         32      Guayaquil  ...           4387434  0.519368
32         33        Quevedo  ...            921763  0.163629
33         34      Guayaquil  ...           4387434  0.519368
34         35         Playas  ...           4387434  0.007843
35         36       Libertad  ...            401178  0.239151
36         37         Cuenca  ...            881394  0.374325
37         38           Loja  ...            521154  0.326736
38         39         Cuenca  ...            881394  0.374325
39         40        Machala  ...            715751  0.323101
40         41        Machala  ...            715751  0.323101
41         42         Cuenca  ...            881394  0.374325
42         43     Esmeraldas  ...            643654  0.239313
43         44          Quito  ...           3228233  0.498023
44         45          Quito  ...           3228233  0.498023
45         46          Quito  ...           3228233  0.498023
46         47          Quito  ...           3228233  0.498023
47         48          Quito  ...           3228233  0.498023
48         49          Quito  ...           3228233  0.498023
49         50         Ambato  ...            590600  0.279690
50         51      Guayaquil  ...           4387434  0.519368
51         52          Manta  ...           1562079  0.139271
52         53          Manta  ...           1562079  0.139271
53         54      El Carmen  ...           1562079  0.029677

[54 rows x 11 columns]

todav√≠a se puede mejorar, las ciudades y estados se deben pasar a one hot encoder, la poblaci√≥n y desidad se puede clasificar dejando marcas de clases o similares

In [ ]:

du_stores= stores.copy(deep=False)
du_stores.head(2)

   store_nbr   city      state  ... cantones  pob_provincia2020     %_pob
0          1  Quito  Pichincha  ...        8            3228233  0.498023
1          2  Quito  Pichincha  ...        8            3228233  0.498023

[2 rows x 11 columns]

In [ ]:
stores["city-state"] = stores["city"] + "-" + stores["state"]
stores['cluster'] = stores['cluster'].astype(str)
stores["cluster"].replace({"5":  "peq",
                           "12": "peq",
                           "16": "peq",
                           "17": "peq"}, inplace=True)

stores["cluster"] = stores["cluster"] + "-cluster"
stores["type"] = stores["type"] + "-type"

stores["state"].replace({"Esmeraldas": "pob_peq",
                         "Chimborazo": "pob_peq", 
                         "Loja":"pob_peq",
                         "Imbabura":"pob_peq",
                         "Santa Elena":"pob_peq",
                         "Bolivar":"pob_peq",
                         "Pastaza":"pob_peq"}, inplace=True)

stores["city"].replace({"Esmeraldas": "city_peq",
                        "Riobamba": "city_peq", 
                        "Loja":"city_peq",
                        "Ibarra":"city_peq",
                        "Salinas":"city_peq",
                        "Bolivar":"city_peq",
                        "Pastaza":"city_peq"}, inplace=True)

stores["city-state"] = stores["city"] + "-" + stores["state"]
stores.head(2)

   store_nbr   city      state  ... pob_provincia2020     %_pob       city-state
0          1  Quito  Pichincha  ...           3228233  0.498023  Quito-Pichincha
1          2  Quito  Pichincha  ...           3228233  0.498023  Quito-Pichincha

[2 rows x 12 columns]

In [ ]:
stores.to_csv('drive/MyDrive/store_sales/stores_rev.csv')

In [ ]:
one_hot= pd.get_dummies(stores["city-state"])
stores=stores.join(one_hot)

In [ ]:
one_hot= pd.get_dummies(stores["state"])
stores=stores.join(one_hot)

In [ ]:
one_hot= pd.get_dummies(stores["cluster"])
stores=stores.join(one_hot)

In [ ]:
one_hot= pd.get_dummies(stores["type"])
stores=stores.join(one_hot)

In [ ]:
stores.head(2)

   store_nbr   city      state    type  ... B-type  C-type  D-type  E-type
0          1  Quito  Pichincha  D-type  ...      0       0       1       0
1          2  Quito  Pichincha  D-type  ...      0       0       1       0

[2 rows x 59 columns]

In [ ]:
#create the one hot encoder for state y city state
stores.drop(["city","state","city-state","cluster","type"],axis=1, inplace=True)

In [ ]:
stores.head(2)

   store_nbr  Poblaci√≥n(2010)  capital  ...  C-type  D-type  E-type
0          1          1607734        1  ...       0       1       0
1          2          1607734        1  ...       0       1       0

[2 rows x 54 columns]

los datos ser√°n guardados para ser usados en otro libro

In [ ]:
stores["%_pob"] = round(stores["%_pob"],2)
stores["den_provincia"] = round(stores["den_provincia"],2)

stores.to_csv('drive/MyDrive/store_sales/stores_add.csv')

In [ ]:
stores.head()

   store_nbr  Poblaci√≥n(2010)  capital  ...  C-type  D-type  E-type
0          1          1607734        1  ...       0       1       0
1          2          1607734        1  ...       0       1       0
2          3          1607734        1  ...       0       1       0
3          4          1607734        1  ...       0       1       0
4          5           270875        1  ...       0       1       0

[5 rows x 54 columns]

In [ ]:
print(len(stores.dtypes))

54

In [ ]:
#